export const BlocksNames = {
  Language: 'language',
  MainInfo: 'mainInfo',
  InvestInfo: 'investInfo',
  Partners: 'partners',
  EventFormat: 'eventFormat',
  Roles: 'roles',
  Promo: 'promo',
  Payment: 'payment',
  FinalInfo: 'finalInfo',
  VcForm: 'vcForm',
  StartupForm: 'startupForm',
  Company: 'company',
  GuestTickets: 'guestTickets',
} as const
